# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 10, 171, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(150, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(80, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(230, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(230, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_times = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_times.setGeometry(QtCore.QRect(230, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_times.setFont(font)
        self.pushButton_times.setObjectName("pushButton_times")
        self.pushButton_divide = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divide.setGeometry(QtCore.QRect(230, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_C.setGeometry(QtCore.QRect(180, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_equals = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_equals.setGeometry(QtCore.QRect(240, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setObjectName("pushButton_equals")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_1.clicked.connect(self.pr1)
        self.pushButton_2.clicked.connect(self.pr2)
        self.pushButton_3.clicked.connect(self.pr3)
        self.pushButton_4.clicked.connect(self.pr4)
        self.pushButton_5.clicked.connect(self.pr5)
        self.pushButton_6.clicked.connect(self.pr6)
        self.pushButton_7.clicked.connect(self.pr7)
        self.pushButton_8.clicked.connect(self.pr8)
        self.pushButton_9.clicked.connect(self.pr9)
        self.pushButton_0.clicked.connect(self.pr0)

        self.pushButton_plus.clicked.connect(self.prPlus)
        self.pushButton_minus.clicked.connect(self.prMinus)
        self.pushButton_times.clicked.connect(self.prTimes)
        self.pushButton_divide.clicked.connect(self.prDivide)

        self.pushButton_C.clicked.connect(self.prC)
        self.pushButton_equals.clicked.connect(self.prEquals)

        self.display = ''

        self.result = '0'
        self.next_calc = '+'

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_times.setText(_translate("MainWindow", "x"))
        self.pushButton_divide.setText(_translate("MainWindow", "/"))
        self.pushButton_C.setText(_translate("MainWindow", "C"))
        self.pushButton_equals.setText(_translate("MainWindow", "="))

    def calc1(self,num):
        if self.next_calc == '+':
            self.result = str(int(self.result)+num)
        if self.next_calc == '-':
            self.result = str(int(self.result)-num)
        if self.next_calc == '*':
            self.result = str(int(self.result)*num)
        if self.next_calc == '/':
            self.result = str(int(self.result)/num)

    def pr1(self):
        self.display =self.display + "1"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(1)
    def pr2(self):
        self.display =self.display + "2"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(2)
    def pr3(self):
        self.display =self.display + "3"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(3)
    def pr4(self):
        self.display =self.display + "4"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(4)
    def pr5(self):
        self.display =self.display + "5"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(5)
    def pr6(self):
        self.display =self.display + "6"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(6)
    def pr7(self):
        self.display =self.display + "7"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(7)
    def pr8(self):
        self.display =self.display + "8"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(8)
    def pr9(self):
        self.display =self.display + "9"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(9)
    def pr0(self):
        self.display =self.display + "0"
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.calc1(0)

    def prPlus(self):
        self.display = ""
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.next_calc = '+'
    def prMinus(self):
        self.display =""
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.next_calc = '-'
    def prTimes(self):
        self.display =""
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.next_calc = '*'
    def prDivide(self):
        self.display =""
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.next_calc = '/'

    def prC(self):
        self.display =""
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.result = 0
    def prEquals(self):
        self.display =self.result
        self.lcd = self.lcdNumber
        self.lcdNumber.display(self.display)
        self.result = 0
        self.display = ""
        self.next_calc = '+'




if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
